apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  generation: 1
  labels:
    app: harbor-exporter
  name: harbor-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      containers:
      - command:
        - /bin/harbor-exporter
        - -username admin
        - -password Harbor12345
        - -harbor-address harbor.aibee.cn
        image: harbor.aibee.cn/platform/harbor-exporter:dev
        imagePullPolicy: Always
        name: harbor-exporter
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: "500m"
            memory: 512Mi
        securityContext:
          privileged: false
          procMount: Default
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30