apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9001"
  labels:
    app: harbor-exporter
    k8s-app: harbor-exporter
  name: harbor-exporter
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: harbor-exporter
  sessionAffinity: None
  type: ClusterIP